apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo
  namespace: argocd
spec:
  destination:
    namespace: secure-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dev/hello-world-dev
    repoURL: https://github.com/Elyas09/secure-demo
    targetRevision: main
  sync:
    comparedTo:
      destination:
        namespace: secure-demo
        server: https://kubernetes.default.svc
      source:
        path: dev/
        repoURL: https://github.com/Elyas09/secure-demo
        targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
